# Copyright 2020 Wintex
# SPDX-License-Identifier: LGPL-3.0-only

site_name: DOTON Docs
site_description: An implementation of a bridge between FreeTON and substrate-based networks

repo_name: wintexpro/chainbridge
repo_url: https://github.com/wintexpro/chainbridge

# Configuration
markdown_extensions:
  - meta
  - admonition
  - codehilite
  - toc:
      permalink: true

theme:
  name: material
  palette:
    primary: black
  favicon: img/favicon.ico
nav:
  - Installation: installation.md
  - Configuration:
    - Overview: configuration.md
    - CLI Options: cli-options.md
  - Specification:
      - ChainBridge: spec.md
      - Substrate: chains/substrate.md
  - Running Locally: local.md

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/wintexpro/chainbridge